version: '2'
services:
    jenkins:
        image: jenkins-master:latest
        privileged: true
        restart: always
        ports:
        - "8085:8080"
        - "50000:50000"
        volumes:
            - jenkins-data:/var/jenkins_home/
            - /var/run/docker.sock:/var/run/docker.sock
    jenkins-nodejs:
        image: jenkins-nodejs
        privileged: true
        ports:
            - 22
        volumes_from:
            - jenkins
    jenkins-maven:
        image: jenkins-maven
        privileged: true
        ports:
            - 22
        volumes_from:
            - jenkins
    jenkins-gradle:
        image: jenkins-gradle
        privileged: true
        ports:
            - 22
        volumes_from:
            - jenkins
volumes:
    jenkins-data:
        driver: local
