version: '2'
services:
    jenkins:
        image: jenkins-master
        privileged: true
        restart: always
        ports:
        - "8085:8080"
        - "50000:50000"
        volumes:
            - jenkins-data:/var/jenkins_home/
            - /var/run/docker.sock:/var/run/docker.sock
        command: "docker exec -i dojo-jenkins_jenkins_1 echo 'lts' > /usr/share/jenkins/ref/jenkins.install.UpgradeWizard.state"
        # command: "docker exec -i dojo-jenkins_jenkins_1 echo 'lts' > /usr/share/jenkins/ref/jenkins.install.InstallUtil.lastExecVersion"
    jenkins-nodejs:
        image: jenkins-nodejs
        privileged: true
        ports:
            - 22
        volumes_from:
            - jenkins
    jenkins-maven:
        image: jenkins-maven
        privileged: true
        ports:
            - 22
        volumes_from:
            - jenkins
    jenkins-gradle:
        image: jenkins-gradle
        privileged: true
        ports:
            - 22
        volumes_from:
            - jenkins
volumes:
    jenkins-data:
        driver: local
